### PR TITLE
Added directive and vue component data snippets

### PR DESCRIPTION
**Pull request by tiagolr**
I think it's looking good, the directive snippets are specially helpful, try for yourself.

Some directive and other snippets are missing which I'll add as i need them, cheers.

### CODE REVIEW

**Comment by filipelinhares** [comment]
Thanks man, now you're a collaborator :smile:

**Comment by tiagolr** [comment]
Thanks hehe, I don't know if you are using Vue + vue snippets atm but the directive snippets for html are damn useful. Cheers.

**Comment by filipelinhares** [comment]
I'm not using Vue anymore. I'm studying other things to use in my job :disappointed:

**Comment by tiagolr** [comment]
Oh well, I'm happy to have introduced vuejs to the company I'm in, tho now the pressure is on me when something is not right so no easy routes.. abraco, depois faz update no packagecontrol.io qdo puderes a package ja diz la "trending" heheh, fica bem.

**Comment by filipelinhares** [comment]
Do you have any other snippet which you want to add? I want to add a `1.0.0` release and update the package.io :smile:

**Comment by tiagolr** [comment]
I think it's fine for a 1.0.0 release, there are directives there are not there but it's a good release as it is. ( Normally i only add snippets as i need/use them)

**Pull request merged**
